spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.106.140:3306/crawl
    username: root
    password: LingYi01@Nb
  jpa:
    database: mysql
    show-sql: true
#server:
#  port: 80
#  tomcat:
#    uri-encoding: UTF-8 # tomcat的URI编码
#    max-http-header-size: 100000